instanceName: exampleGenerate
contactAddress: funcoup@scilifelab.se
examplesPerSpecies:
  9606: JUN
  83333: P0A964 #P00954 #P10346
  559292: P04050 #P02557 #P06778
  122586: Q9K062
  243232: Q59046
  273057: Q97U22
  83332: O53873
  7227: Q8SXI2
  387092: A6Q1M4
  2697049: Spike

exampleQuery: 'JUN' #'P10346' #'P0A7S9' #'P04994' #'P0AEP9' #'P07492' #'ABL1,ABL2,AKT2,NPM1,RUNX1,RUNX1T1,BCL2,BCL3,BCL6,BCR,MYC,DEK,NUP214,PBX1,TCF3,EGFR,MLLT1,FUS,ERBB2,ETS1,EWSR1,FOS,FES,GNAS,JUN,FGFR2,LCK,NFKB2,MDM2,KMT2A,MYB,MYH11,CBFB,PIM1,CCND1,RAF1,REL,SKI,PDGFB,SET,NUP214,SRC,TAL1,NOTCH1,TIAM1,TSC2,NTRK1' #UsherSyndrome: USH1K,CDH23,USH1C,USH1G,MYO7A,PCDH15,USH1E,USH1H,CIB2,ESPN #Lamellar ichthyosis: SULT2B1,ASPRV1,SDR9C7,ABCA12,ALOX12B,ALOXE3,TGM1,CYP4F22,NIPAL4,LIPN
exampleQueryMaxLink: 'AKT1 BRCA1 BRCA2 BRIP1 CHEK2 EP300 PALB2 RB1 TP53'
exampleQueryTOPAS: 'I12R2 NAB1 TIDC1 RA51B KS6A4 MANBA PDGFB DQA2 TNR1A NFKB1 DDX6 IL12A CXCR5 RPL3 IRF8 IRF5 LBR ELMO1 IKZF3 PLCL2 TNPO3'
exampleSpecies: 9606
maxSubnetSize: 500
maxQueryExpanded: 10
# exampleQuerySarsCov2: nsp7 nsp6 nsp11 nsp15 nsp13 orf3a orf7a nsp5 nsp12 nsp14 Spike orf10 nsp9 nsp4 orf9b Envelope nsp8 Nucleoprotein nsp2 orf8 nsp1 Membrane nsp10
exampleQuerySarsCov2: 'AP3A NCAP NS6 NS7A NS7B NS8 ORF10 ORF3B ORF3C ORF3D ORF9B ORF9C R1A R1AB SPIKE VEMP VME1'
covidInstance: 2
anubixCutoff: 0.95
binoxCutoff: 0.95