version: '3.3'

###############################################################################
### Use these configurations for the development server, comment all above #####
###############################################################################

services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=FunCoup
      - POSTGRES_PASSWORD=******* #type your PSW here
      - POSTGRES_DB=FunCoup
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    command: >
      -c work_mem=256MB
      -c maintenance_work_mem=256MB
      -c max_wal_size=2GB
      -c max_connections=500
    logging:
      options:
        max-size: 1g
    shm_size: 100g

volumes:
  db:
  database:

################################################################################
#### Use these configurations for the production server, comment all above #####
################################################################################

# version: '3.3'

# services:
#   funcoup:
#     restart: always
#     build: ./FunCoup
#     command: gunicorn FunCoup.wsgi:application --bind 0.0.0.0:8000 --timeout 600 --workers 5
#     expose:
#       - 8000
#     volumes:
#       - ./FunCoup/website/static/website/:/usr/src/app/website/static/website/
#     logging:
#       options:
#         max-size: 1g

#   nginx:
#     restart: always
#     build: ./nginx
#     ports:
#       - 80:80
#       - 443:443
#     depends_on:
#       - funcoup
#     volumes:
#       - ./FunCoup/website/static/:/home/app/web/staticfiles
#       - ./nginx/:/etc/nginx/conf.d/:ro
#       - ./certbot/www:/etc/letsencrypt/live/funcoup6.scilifelab.se/:ro
#       - ./certbot/conf/:/etc/letsencrypt
#     logging:
#       options:
#         max-size: 1g

#   certbot:
#     #restart: always
#     image: certbot/certbot:latest
#     volumes:
#       - ./certbot/www:/var/www/certbot/:rw
#       - ./certbot/conf/:/etc/letsencrypt/:rw
#     logging:
#       options:
#         max-size: 1g


#   db:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=FunCoup
#       - POSTGRES_PASSWORD=******* #type your PSW here
#       - POSTGRES_DB=FunCoup
#       - "POSTGRES_HOST_AUTH_METHOD=trust"
#     expose:
#       - 5432
#     volumes: 
#       - ./database:/var/lib/postgresql/data
#     command: >
#       -c work_mem=256MB
#       -c maintenance_work_mem=256MB
#       -c max_wal_size=2GB
#       -c max_connections=500
#     logging:
#       options:
#         max-size: 1g

# volumes:
#   db:
#   database:
#   certbot:
#   nginx: