name: pyfuncoup
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - boltons=23.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cffi=1.15.1
  - chardet=5.2.0
  - conda=23.7.4
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.3
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.3
  - packaging=23.1
  - pip=22.3.1
  - pluggy=1.0.0
  - pycosat=0.6.6
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.8
  - python_abi=3.10
  - readline=8.1.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - setuptools=66.0.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.65.0
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - zstandard=0.19.0
  - pip:
      - asgiref==3.6.0
      - asttokens==2.2.1
      - backcall==0.2.0
      - biopython==1.81
      - certifi==2023.5.7
      - charset-normalizer==3.0.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - connectorx==0.3.2
      - contourpy==1.0.7
      - cycler==0.11.0
      - dask==2023.1.1
      - decorator==5.1.1
      - dill==0.3.7
      - django==4.1.1
      - django-postgres-copy==2.7.2
      - et-xmlfile==1.1.0
      - executing==1.2.0
      - fonttools==4.39.3
      - fsspec==2023.4.0
      - geoparse==2.0.3
      - greenlet==3.0.1
      - igraph==0.11.3
      - ipython==8.12.0
      - jedi==0.18.2
      - joblib==1.2.0
      - kdepy==1.1.0
      - kiwisolver==1.4.4
      - llvmlite==0.41.1
      - locket==1.0.0
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - msgpack==1.0.5
      - networkx==3.0
      - numba==0.58.1
      - numpy==1.24.1
      - obonet==1.0.0
      - openpyxl==3.1.2
      - pandarallel==1.6.5
      - pandas==1.5.2
      - parso==0.8.3
      - partd==1.4.0
      - patsy==0.5.4
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - polars-lts-cpu==0.19.15
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - psycopg2-binary==2.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==14.0.1
      - pybedtools==0.9.1
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pysam==0.22.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - requests==2.28.2
      - scikit-learn==1.2.2
      - scipy==1.10.0
      - seaborn==0.12.2
      - six==1.16.0
      - sqlalchemy==2.0.23
      - sqlparse==0.4.3
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - swifter==1.4.0
      - texttable==1.7.0
      - threadpoolctl==3.1.0
      - traitlets==5.9.0
      - types-chardet==5.0.4.6
      - typing-extensions==4.8.0
      - urllib3==1.26.14
      - wcwidth==0.2.6
      - wget==3.2
